# Generated by Django 5.0.14 on 2026-09-30 08:44

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import rental.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
            ],
            options={
                'verbose_name': 'หมวดหมู่อุปกรณ์',
                'verbose_name_plural': 'หมวดหมู่อุปกรณ์',
            },
        ),
        migrations.CreateModel(
            name='PenaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdue_days_threshold', models.PositiveSmallIntegerField(default=1, verbose_name='เกินกำหนดตั้งแต่ (วัน) ถึงจะได้รับบทลงโทษ')),
                ('suspension_days', models.PositiveSmallIntegerField(default=2, verbose_name='จำนวนวันพักสิทธิ์')),
                ('booking_expire_hours', models.PositiveSmallIntegerField(default=24, verbose_name='เวลาหมดอายุการจองก่อนมารับ (ชั่วโมง)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ตั้งค่าระบบบทลงโทษ',
                'verbose_name_plural': 'ตั้งค่าระบบบทลงโทษ',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'นักศึกษา'), ('staff', 'เจ้าหน้าที่')], default='student', max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='รหัสนักศึกษา')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='ถูกพักสิทธิ์ชั่วคราว')),
                ('suspended_until', models.DateField(blank=True, null=True, verbose_name='พักสิทธิ์ถึงวันที่')),
                ('suspended_reason', models.CharField(blank=True, max_length=255, verbose_name='เหตุผลที่พักสิทธิ์')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', rental.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่ออุปกรณ์')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='รูปภาพ')),
                ('max_borrow_days', models.PositiveSmallIntegerField(default=7, verbose_name='จำนวนวันยืมสูงสุดต่อครั้ง')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดงในรายการยืม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_list', to='rental.equipmentcategory')),
            ],
            options={
                'verbose_name': 'อุปกรณ์ (รุ่น)',
                'verbose_name_plural': 'อุปกรณ์ (รุ่น)',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='หมายเลขเครื่อง/ทรัพย์สิน')),
                ('status', models.CharField(choices=[('available', 'ว่าง'), ('reserved', 'ถูกจอง'), ('borrowed', 'ถูกยืมอยู่'), ('disabled', 'ปิดใช้งาน')], db_index=True, default='available', max_length=10)),
                ('condition_note', models.TextField(blank=True, verbose_name='หมายเหตุสภาพอุปกรณ์ (ล่าสุด)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rental.equipment')),
            ],
            options={
                'verbose_name': 'อุปกรณ์ (ชิ้น)',
                'verbose_name_plural': 'อุปกรณ์ (ชิ้น)',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(default=rental.models.generate_booking_code, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('awaiting_pickup', 'รอรับของ'), ('borrowed', 'กำลังยืม'), ('overdue', 'เกินกำหนด'), ('returned', 'คืนแล้ว'), ('cancelled', 'ยกเลิก')], db_index=True, default='awaiting_pickup', max_length=20)),
                ('requested_start_date', models.DateField(verbose_name='วันที่เริ่มยืม')),
                ('requested_end_date', models.DateField(verbose_name='วันครบกำหนดคืน')),
                ('booking_expires_at', models.DateTimeField(verbose_name='หมดอายุการจอง (ต้องมารับก่อน)')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลารับอุปกรณ์จริง')),
                ('pickup_condition_note', models.TextField(blank=True, verbose_name='สภาพอุปกรณ์ตอนส่งมอบ')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาคืนอุปกรณ์จริง')),
                ('return_condition_note', models.TextField(blank=True, verbose_name='สภาพอุปกรณ์ตอนคืน')),
                ('overdue_days_at_return', models.PositiveSmallIntegerField(default=0, verbose_name='จำนวนวันที่คืนเกินกำหนด')),
                ('penalty_applied', models.BooleanField(default=False, verbose_name='โดนบทลงโทษหรือไม่')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, choices=[('by_student', 'ยกเลิกโดยนักศึกษา'), ('no_show', 'ระบบยกเลิกอัตโนมัติ (ไม่มารับตามเวลา)')], max_length=20)),
                ('last_reminder_sent_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by_pickup', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_confirmed_pickup', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by_return', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_confirmed_return', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rental.equipmentunit')),
            ],
            options={
                'verbose_name': 'การจอง/ยืม',
                'verbose_name_plural': 'การจอง/ยืม',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('booking_confirmed', 'จองสำเร็จ'), ('pickup_success', 'รับของสำเร็จ'), ('password_reset_requested', 'ขอลิงก์ตั้งรหัสผ่านใหม่'), ('reminder_due_soon', 'ใกล้ครบกำหนด (เหลือ 1 วัน)'), ('reminder_due_today', 'ถึงวันครบกำหนด'), ('reminder_overdue', 'เกินกำหนด (แจ้งซ้ำรายวัน)'), ('suspended', 'ถูกพักสิทธิ์'), ('return_success', 'คืนสำเร็จ'), ('auto_cancelled', 'ยกเลิกอัตโนมัติ (ไม่มารับ)')], max_length=25)),
                ('email_to', models.EmailField(max_length=254)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rental.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ประวัติการแจ้งเตือน',
                'verbose_name_plural': 'ประวัติการแจ้งเตือน',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'requested_end_date'], name='rental_book_status_03883c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'booking_expires_at'], name='rental_book_status_edebce_idx'),
        ),
    ]
