# Generated by Django 5.0.14 on 2026-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์'),
        ),
    ]
