# Generated by Django 5.0.14 on 2026-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='trigger',
            field=models.CharField(choices=[('booking_confirmed', 'จองสำเร็จ'), ('pickup_success', 'รับของสำเร็จ'), ('password_reset_requested', 'ขอลิงก์ตั้งรหัสผ่านใหม่'), ('reminder_due_soon', 'ใกล้ครบกำหนด (เหลือ 1 วัน)'), ('reminder_due_today', 'ถึงวันครบกำหนด'), ('reminder_overdue', 'เกินกำหนด (แจ้งซ้ำรายวัน)'), ('suspended', 'ถูกพักสิทธิ์'), ('return_success', 'คืนสำเร็จ'), ('auto_cancelled', 'ยกเลิกอัตโนมัติ (ไม่มารับ)'), ('cancelled_by_student', 'นักศึกษายกเลิกเอง')], max_length=25),
        ),
    ]
